# Generated by Django 3.2.15 on 2023-08-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated', models.DateField(auto_now=True, verbose_name='Last modified')),
                ('delivered', models.DateField(verbose_name='Delivery date')),
                ('issued', models.DateField(verbose_name='Date of issue')),
                ('payment_date', models.DateField(verbose_name='The payment date')),
                ('payment_method', models.PositiveSmallIntegerField(choices=[(0, 'Cash'), (1, 'Transfer')], verbose_name='Payment method')),
                ('order', models.IntegerField(default=0)),
                ('number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Goods or service')),
                ('number', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Number of items')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit price without tax')),
                ('net', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Net amount')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tax amount')),
                ('gross', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Gross amount')),
            ],
        ),
    ]
