# Generated by Django 4.0.1 on 2022-02-13 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(help_text='Make and model', max_length=250, verbose_name='make')),
                ('registration_date', models.DateField(help_text='Date of first registratrion in Poland')),
                ('vin_number', models.CharField(help_text='Chassis number / VIN / SN number', max_length=50, unique=True)),
                ('axles', models.IntegerField(blank=True, verbose_name='Number of axles')),
                ('production_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('weight', models.FloatField(blank=True, help_text='Vehicle weight (if semi-tractor)', verbose_name='Weight')),
                ('gvm', models.FloatField(blank=True, help_text='Maximum permissible laden weight', verbose_name='Gross vehicle mass')),
                ('gcwr', models.FloatField(blank=True, help_text='maximum permissible laden weight of a vehicle combination', verbose_name='Gross combined weight rating')),
                ('suspension', models.CharField(choices=[('1', 'Air suspension'), ('2', 'Equivalent to air suspension'), ('3', 'Other')], max_length=10)),
                ('type', models.CharField(choices=[('1', 'Lorry'), ('2', 'Truck-tractor'), ('3', 'Ballast tractor'), ('4', 'Trailer'), ('5', 'Semi-trailer'), ('6', 'Bus')], max_length=10)),
            ],
        ),
    ]
