# Generated by Django 4.0.1 on 2022-02-13 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentvehicle',
            name='model',
            field=models.CharField(help_text='Make and model', max_length=250, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='documentvehicle',
            name='production_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Production year'),
        ),
        migrations.AlterField(
            model_name='documentvehicle',
            name='registration_date',
            field=models.DateField(help_text='Date of first registratrion in Poland', verbose_name='Registration'),
        ),
        migrations.AlterField(
            model_name='documentvehicle',
            name='type',
            field=models.CharField(choices=[('1', 'Lorry'), ('2', 'Truck-tractor'), ('3', 'Ballast tractor'), ('4', 'Trailer'), ('5', 'Semi-trailer'), ('6', 'Bus')], max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='documentvehicle',
            name='vin_number',
            field=models.CharField(help_text='Chassis number / VIN / SN number', max_length=50, unique=True, verbose_name='VIN'),
        ),
    ]
