# Generated by Django 4.0.1 on 2022-02-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_alter_documentvehicle_axles_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentvehicle',
            options={'verbose_name': 'Vehicle'},
        ),
        migrations.AddField(
            model_name='documentvehicle',
            name='registration_plate',
            field=models.CharField(default='', help_text='License plate number of the vehicle', max_length=25, verbose_name='Number plate'),
        ),
    ]
