# Generated by Django 4.0.1 on 2022-02-17 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_remove_documentvehicle_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentvehicle',
            name='company',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='vehicle.company'),
            preserve_default=False,
        ),
    ]
