# Generated by Django 4.0.1 on 2022-02-17 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_documentvehicle_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentvehicle',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='vehicle.company'),
        ),
    ]
