# Generated by Django 4.0.3 on 2022-03-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_alter_documentvehicle_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.CharField(max_length=4)),
                ('tax_authority', models.CharField(max_length=250)),
                ('tax_payer_name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Document',
            },
        ),
    ]
