# Generated by Django 4.0.3 on 2022-03-30 21:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', 'Owner'), ('1', 'Co-owner - first named in the vehicle registration card'), ('2', 'Co-owner - second named in the vehicle registration card')], default='0', max_length=1)),
                ('percentage', models.IntegerField(default=100, verbose_name='Percentage of ownership')),
                ('purchase_date', models.DateField(verbose_name='Purchase date')),
                ('sell_date', models.DateField(blank=True, verbose_name='Date of sell')),
                ('deregistration_date', models.DateField(blank=True, verbose_name='Date of deregistration')),
            ],
            options={
                'verbose_name': 'Ownerspip',
                'verbose_name_plural': 'Ownersphips',
            },
        ),
        migrations.AlterModelOptions(
            name='documentvehicle',
            options={'verbose_name': 'DocumentVehicle'},
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('1', 'Lorry'), ('2', 'Truck-tractor'), ('3', 'Ballast tractor'), ('4', 'Trailer'), ('5', 'Semi-trailer'), ('6', 'Bus')], max_length=10)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_model', to='vehicle.manufacturer')),
            ],
            options={
                'verbose_name': 'Vehicle model',
                'verbose_name_plural': 'Vehicles models',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(help_text='Date of first registratrion in Poland')),
                ('vin_number', models.CharField(help_text='Chassis number / VIN / SN number', max_length=50, unique=True)),
                ('axles', models.IntegerField(blank=True, verbose_name='Number of axles')),
                ('production_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('weight', models.FloatField(blank=True, help_text='Vehicle weight (if semi-tractor)', verbose_name='Weight')),
                ('gvm', models.FloatField(blank=True, help_text='Maximum permissible laden weight', verbose_name='Gross vehicle mass')),
                ('gcwr', models.FloatField(blank=True, help_text='maximum permissible laden weight of a vehicle combination', verbose_name='Gross combined weight rating')),
                ('suspension', models.CharField(choices=[('1', 'Air suspension'), ('2', 'Equivalent to air suspension'), ('3', 'Other')], max_length=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle', to='vehicle.vehiclemodel')),
            ],
        ),
    ]
