# Generated by Django 4.0.3 on 2022-03-30 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_manufacturer_ownership_alter_documentvehicle_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Registration date')),
                ('end_date', models.DateField(verbose_name='Deregistrarion date')),
                ('plate', models.CharField(max_length=25, verbose_name='Registration plate')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='vehicle.registration'),
        ),
    ]
