# Generated by Django 4.0.3 on 2022-03-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0012_registration_vehicle_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Deregistrarion date'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Registration date'),
        ),
    ]
