# Generated by Django 4.0.3 on 2022-03-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0013_alter_registration_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='plate',
            field=models.CharField(max_length=25, unique=True, verbose_name='Registration plate'),
        ),
    ]
