# Generated by Django 4.0.3 on 2022-03-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0014_alter_registration_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='axles',
            field=models.IntegerField(blank=True, default=2, verbose_name='Number of axles'),
        ),
    ]
