# Generated by Django 4.0.3 on 2022-03-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0015_alter_vehicle_axles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='gcwr',
            field=models.FloatField(blank=True, default=0, help_text='maximum permissible laden weight of a vehicle combination', verbose_name='Gross combined weight rating'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='weight',
            field=models.FloatField(blank=True, default=0, help_text='Vehicle weight (if semi-tractor)', verbose_name='Weight'),
        ),
    ]
