# Generated by Django 4.0.3 on 2022-03-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0016_alter_vehicle_gcwr_alter_vehicle_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='axles',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='Number of axles'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='gcwr',
            field=models.FloatField(blank=True, default=0, help_text='maximum permissible laden weight of a vehicle combination', null=True, verbose_name='Gross combined weight rating'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='gvm',
            field=models.FloatField(blank=True, default=0, help_text='Maximum permissible laden weight', null=True, verbose_name='Gross vehicle mass'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='weight',
            field=models.FloatField(blank=True, default=0, help_text='Vehicle weight (if semi-tractor)', null=True, verbose_name='Weight'),
        ),
    ]
