# Generated by Django 4.0.3 on 2022-03-30 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0017_alter_vehicle_axles_alter_vehicle_gcwr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='registration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='vehicle.registration'),
        ),
    ]
