# Generated by Django 4.0.3 on 2022-03-30 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0018_alter_vehicle_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='registration_date',
            new_name='first_registration',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='vehicle.registration'),
        ),
    ]
