# Generated by Django 4.0.3 on 2022-03-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0019_rename_registration_date_vehicle_first_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='plate',
            field=models.CharField(max_length=25, verbose_name='Registration plate'),
        ),
    ]
