# Generated by Django 4.0.3 on 2022-04-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0020_alter_registration_plate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownership',
            options={'verbose_name': 'Ownership', 'verbose_name_plural': 'Ownersphips'},
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='type',
            field=models.CharField(choices=[('1', 'Lorry'), ('2', 'Truck-tractor'), ('3', 'Ballast tractor'), ('4', 'Trailer'), ('5', 'Semi-trailer'), ('6', 'Bus'), ('0', 'Other')], max_length=10),
        ),
    ]
