# Generated by Django 4.0.3 on 2022-04-22 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0022_registration_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='registration',
        ),
        migrations.AddField(
            model_name='registration',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='vehicle.vehicle'),
        ),
        migrations.DeleteModel(
            name='DocumentVehicle',
        ),
    ]
