# Generated by Django 4.0.3 on 2022-04-22 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0023_delete_document_remove_vehicle_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now, null=True, verbose_name='Registration date'),
        ),
    ]
