# Generated by Django 4.0.3 on 2022-04-30 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0024_alter_registration_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='vehicle.vehicle'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Registration date'),
        ),
    ]
