# Generated by Django 4.0.3 on 2022-04-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0025_ownership_vehicle_alter_registration_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
