# Generated by Django 4.0.3 on 2022-05-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0026_registration_active'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('plate', 'start_date'), name='unuque_plate'),
        ),
    ]
