# Generated by Django 4.0.3 on 2022-05-01 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0027_registration_unuque_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='active',
        ),
    ]
