# Generated by Django 4.0.3 on 2022-05-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0028_remove_registration_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
