# Generated by Django 4.0.3 on 2022-07-24 19:29

from django.db import migrations, models
import vehicle.validators


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0030_alter_vehiclemodel_options_alter_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='start_date',
            field=models.DateField(null=True, validators=[vehicle.validators.validate_future_date], verbose_name='Registration date'),
        ),
    ]
