# Generated by Django 4.0.3 on 2022-08-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0031_alter_registration_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='File')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='title')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateField(auto_now=True, verbose_name='Updated')),
                ('vehicle', models.ManyToManyField(blank=True, null=True, related_name='vehicle', to='vehicle.vehicle', verbose_name='Vehicle')),
            ],
        ),
    ]
