# Generated by Django 4.0.3 on 2022-08-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0031_alter_registration_start_date'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='vehicle',
            field=models.ManyToManyField(blank=True, related_name='vehicle', to='vehicle.vehicle', verbose_name='Vehicle'),
        ),
    ]
