# Generated by Django 4.0.3 on 2022-08-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
