# Generated by Django 3.2.15 on 2023-08-30 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Date of creation')),
                ('updated', models.DateField(auto_now=True, verbose_name='Last modified')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=250, null=True, unique=True, verbose_name='Name')),
                ('short_name', models.CharField(max_length=250, null=True, unique=True, verbose_name='Short name')),
                ('nip', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Tax number')),
                ('vies', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Vies number')),
                ('regon', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Regon number')),
                ('pesel', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='PESEL number')),
                ('vat_payer', models.BooleanField()),
                ('remarks', models.CharField(blank=True, max_length=250, null=True, verbose_name='Remarks')),
                ('type', models.CharField(blank=True, max_length=3, null=True, verbose_name='Type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Date of creation')),
                ('updated', models.DateField(auto_now=True, verbose_name='Last modified')),
                ('active', models.BooleanField(default=True)),
                ('city', models.CharField(max_length=250, verbose_name='City / town')),
                ('street', models.CharField(max_length=250, verbose_name='Street')),
                ('number', models.CharField(max_length=25, verbose_name='House number')),
                ('flat', models.CharField(max_length=25, verbose_name='Flat number')),
                ('postal_code', models.CharField(max_length=25, verbose_name='Zip code')),
                ('country_code', models.CharField(max_length=3, verbose_name='Country code')),
                ('region', models.CharField(max_length=250, verbose_name='Region')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='companies.company')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'abstract': False,
            },
        ),
    ]
