# Generated by Django 3.2.15 on 2023-07-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('plate', 'active'), name='unique_plate'),
        ),
    ]
