# Generated by Django 3.2.15 on 2023-07-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_registration_unique_plate'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registration',
            name='unuque_plate',
        ),
        migrations.RemoveConstraint(
            model_name='registration',
            name='unique_plate',
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('plate', 'start_date'), name='unique_plate'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('plate', 'active'), name='unique_active_plate'),
        ),
    ]
